FROM centos:8

ENV TZ UTC
ENV PORT 8080
ENV SCRIPTS_DIR /root/agent
ENV HTTPS_DIR $SCRIPTS_DIR/https
ENV WORKSPACE $SCRIPTS_DIR
ENV TEMPLATES_DIR $WORKSPACE/templates
ENV VARS_DIR $WORKSPACE/variables

#click env vars
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

WORKDIR $SCRIPTS_DIR

COPY inputs/templates/ $TEMPLATES_DIR/
COPY inputs/variables/ $VARS_DIR/

COPY dist/main $SCRIPTS_DIR
#copy runcmd exec for the commands executed in background
ADD https://estuary-agent-go.s3.eu-central-1.amazonaws.com/4.1.0/runcmd-linux $SCRIPTS_DIR/runcmd
COPY https/key.pem $HTTPS_DIR/
COPY https/cert.pem $HTTPS_DIR/

# ADD https://github.com/dinuta/estuary-agent-go/releases/download/4.0.1/main-linux $SCRIPTS_DIR
RUN chmod +x $SCRIPTS_DIR/main
RUN chmod +x $SCRIPTS_DIR/runcmd

CMD ["/root/agent/main"]
