version: "3.3"

services:
  estuary-agent:
    container_name: estuary-agent
    image: dinutac/estuary-agent:latest
    hostname: estuary-agent
    #    entrypoint: tail -f /etc/alpine-release
    command: bash -c "sleep 20 && /scripts/main_flask.py"
    environment:
      #      FLUENTD_IP_PORT: '192.168.100.12:24224'
      EUREKA_SERVER: http://eureka-server:8080/eureka/v2 #your eureka server
      APP_IP_PORT: estuary-agent:8080 #your app details: where it is and on which port. needed for service discovery and spread of tests from the test client
    volumes:
      - ./inputs/templates:/scripts/inputs/templates
      - ./inputs/variables:/scripts/inputs/variables
    #      - ./:/scripts/
    #      - ./tmp:/tmp
    ports:
      - "8080:8080"

    expose:
      - "8080"


  eureka-server:
    container_name: eureka-server
    image: dinutac/netflixoss-eureka:1.9.21
    hostname: eureka-server
#    ports:
#      - "8081:8080"
    expose:
      - "8080"