version: "3.3"

services:
  estuary-testrunner:
    container_name: estuary-testrunner
    image: dinutac/estuary-testrunner:latest
    hostname: estuary-testrunner
#    entrypoint: tail -f /etc/alpine-release
    command: bash -c "/home/dev/scripts/wait-for-it.sh -t 20 eureka-server:8080 -- echo \"eureka running\" && sleep 20 && python3 /home/dev/scripts/main_flask.py"
    environment:
#      FLUENTD_IP_PORT: '192.168.100.12:24224'
      EUREKA_SERVER: http://eureka-server:8080/eureka/v2 #your eureka server
      APP_IP_PORT: estuary-testrunner:8080 #your app details: where it is and on which port. needed for service discovery and spread of tests from the test client
    volumes:
      - ./inputs/templates:/data
      - ./inputs/variables:/variables
    #      - ./:/home/dev/scripts/
    #      - ./tmp:/tmp
    ports:
      - "8080:8080"

    expose:
      - "8080"


  eureka-server:
    container_name: eureka-server
    image: dinutac/netflixoss-eureka:1.9.15
    hostname: eureka-server
#    ports:
#      - "8081:8080"
    expose:
      - "8080"